fail_fast: true
default_stages: [commit, manual]

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.15.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "."]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.55.0
    hooks:
      - id: terraform_fmt
